### ISSUE TITLE
errata: preface

### ISSUE THREAD

**Issue by WenboSheng** [Liam0205/LaTeX_hard_way#1]
00_preface.tex 源代码 line 9: 

```
但任然不断有同好表示 \LaTeX{} 入门难
```

不通，应该是拼写错了。

**Comment by Liam0205** [comment]
来个 PR 怎么样？

**Comment by WenboSheng** [comment]
啥意思，怎么搞？

**Comment by Liam0205** [comment]
Pull Request

你直接点到源文件里去，然后点右上角的铅笔修改。之后在下面填上 commit 信息，之后一路做下去就好了。

**Comment by Liam0205** [comment]
closed by e6cda1c1748e54d03dabeb05b90755133b986cbe and #2
